### ISSUE TITLE
Faster initial load

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#102]
Especially in js apps (because of babel?) the initial index load of `previews.json` is very slow (like 4 seconds for the default templates.

ideas to speed this up:
1. warm-up on boot: kick off the module loading asynchronously in the preview.ts handler function
2. speedier module loading: try using swc or a different loader rather than babel
3. rust rewrite (jk)

cc @alexfarrill

**Comment by alexfarrill** [comment]
The smoke tests currently includes a `wait_for_previews_json!` since this currently causes cypress tests to incorrectly fail.  When this issues is fixed, that wait can likely be removed
