### ISSUE TITLE
Custom dir at creation is not used for preview server

### ISSUE THREAD

**Issue by tobdru** [sofn-xyz/mailing#114]
Setup:
[Nx app](https://nx.dev/) with react fe and express be (default setup).

Tried with `npx mailing` and `npx mailing init`

What does it look like:
![image](https://user-images.githubusercontent.com/89079833/184227786-fa8a27ac-6893-44af-a486-8e929774a15c.png)

With a quick dive into the code, i could see, that the `targetEmailsDir` is only used in generators.ts.
Where as the previewPaths are only expected in `./src/emails` or` ./emails` (paths.ts).

Solution Ideas:
1. add targetDir arg and remove the question for the dir
2. as the dialog is nice, save the given path in a config file

I would preffer idea 1, as I see its the only variable that needs to be saved (and there are already enough config files ;))

**Comment by psugihara** [comment]
Hey there, thanks for looking at this. It's definitely a bug, apologies. I think the prompt is good for first time users so we should ship the config. 

I'm on the road today, but there's some prior discussion here:

https://github.com/sofn-xyz/mailing/issues/74

**Comment by psugihara** [comment]
Actually i like your idea of killing the prompt and just using the defaults... simpler without the question. I think it's a nice edit.

**Comment by psugihara** [comment]
fixed in #116
