### ISSUE TITLE
Add --emails-dir option

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#115]
Let's add support for specifying `--emails-dir` for all commands. We'll use this same functionality for specifying via config file.

- [x] `--emails-dir` should always be used rather than `getExistingEmailsDir` if it's defined
- [x] kill prompt for emails dir in init, use `--emails-dir` with the defaults as a fallback instead

this will remove the bug in #114, #74, https://github.com/sofn-xyz/mailing/discussions/113

**Comment by mrlubos** [comment]
You're on fire @psugihara!

**Comment by psugihara** [comment]
fixed by @alexfarrill in #116 !
