### ISSUE TITLE
Logging events

### ISSUE THREAD

**Issue by johanolandero** [sofn-xyz/mailing#126]
## Description
When using the built `sendMail` function, it outputs logs for different events such as errors and responses from the configured transport. 
## Problem
My main concern is that I'm no longer in control over which logs gets sent to and how they are transformed as the standard output is `console`. Many server applications uses a centralised source for handling of info/error logs and apply a standardised format, which then gets sent through different configured log transports (such as files, AWS or other).

This could also for example result in poorly managed environments unintentionally sharing PII with a third party.

## Possible solutions
It should probably be up to users of this library to listen to these events and deal with it
- Let users attach a custom message/error handler for events. 
- Place all logs behind `DEBUG` environment variable (this essentially disables possibilities for mailing logs in production environments) 
- Leave event handling to be configured on transport only

I'd love to hear what you think.

**Comment by psugihara** [comment]
Great idea @johanolandero. I'm all for scrubbing personally identifying info from logs and letting you configure logging [on the nodemailer transport](https://nodemailer.com/smtp/#debug-options) (if you want).

Here's one place I see us potentially logging too much: https://github.com/sofn-xyz/mailing/blob/main/packages/core/src/index.ts#L120

Do you have examples of the logs you'd want to scrub? A screenshot with the message would be useful. I want to make sure we're considering them all.

**Comment by johanolandero** [comment]
The code you referenced was definitely the culprit in my case. Seems like the potential error logs is related to preview-stuff which is disabled in production anyway. Thanks @psugihara

**Comment by psugihara** [comment]
awesome, thanks for filing!
