### ISSUE TITLE
Hot reload error Ubuntu

### ISSUE THREAD

**Issue by ludovicoserrani-nautes** [sofn-xyz/mailing#152]
Hi, when I start the preview server on Ubuntu 22.04 (node 14 and node 16) I get this error:

```bash
error starting change watcher TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
```
As a consequence the hot reload is not working and I must start and stop the preview server to reload changes.

Can you please help me?

**Comment by mrlubos** [comment]
Hi @ludovicoserrani-nautes! This is a known caveat with `watch()`, see https://nodejs.org/api/fs.html#caveats. I don't have experience with your platform but I see stat polling mentioned as an acceptable workaround, maybe that could be the fix. Just to confirm, do you use any other libraries that support hot reloading and work on your machine? Are you able to confirm if adding a fallback to stat polling is the correct fix for this issue?

**Comment by ludovicoserrani-nautes** [comment]
Hi @mrlubos, I made this example project of my current situation. As you can see from README i only use npx mailing to start the preview server. How can I add polling to this project? Do you know any libraries that I can use?

**Comment by mrlubos** [comment]
@ludovicoserrani-nautes did you mean to link the project? I can't see any links in your comment. Regardless, I believe the fix would be on the library's side (mailing) so unfortunately there isn't much you can do at this point.

**Comment by ludovicoserrani-nautes** [comment]
Sorry, here it is https://github.com/ludovicoserrani-nautes/mailing-esbuild-node

**Comment by psugihara** [comment]
> Hi, when I start the preview server on Ubuntu 22.04 (node 14 and node 16) I get this error:

Hm, let's try using a more cross-platform friendly alternative to node's `fs.watch`.

Perhaps chokidar? https://github.com/paulmillr/chokidar

**Comment by mrlubos** [comment]
> 

At a quick glance this seems like a suitable alternative. Out of curiosity, how will you test these changes for Ubuntu? Do you use any service or have VM running?

**Comment by psugihara** [comment]
I do not have an ubuntu machine, but would think that it will "just work" if it works on my mac. If it doesn't work for @ludovicoserrani-nautes on the first try, we could boot a little ec2 instance or something to debug.

Here's the line we'd change to use chokidar https://github.com/sofn-xyz/mailing/blob/35af9a5d6b05616bbd795e22dc718f340a405a9b/packages/cli/src/commands/preview/server/start.ts#L163

**Comment by mrlubos** [comment]
@psugihara Could you try to deploy a test release first for @ludovicoserrani-nautes to test? I'm thinking like `v0.7.2-next` or whatever instead of the actual `v0.7.2`. Little bit worried about making it a proper release without testing as the current thing "just works" on a Mac but not on Ubuntu.

**Comment by psugihara** [comment]
yeah that's what i meant (bake an alpha for ludovic).

> worried about making it a proper release without testing as the current thing "just works" on a Mac but not on Ubuntu

that's why it's safe! 😆

**Comment by mrlubos** [comment]
> yeah that's what i meant (bake an alpha for ludovic).
> 
> > worried about making it a proper release without testing as the current thing "just works" on a Mac but not on Ubuntu
> 
> that's why it's safe! 😆

Sounds like a deal if @ludovicoserrani-nautes agrees! 🎉

**Comment by ludovicoserrani-nautes** [comment]
Sure! I can try that as soon as the test release is available. Thank you!

**Comment by psugihara** [comment]
bugfix here to try (release on npm as mailing@0.7.2-next.1).

thanks in advance!

https://github.com/sofn-xyz/mailing/pull/155

**Comment by mrlubos** [comment]
Please let us know if this works @ludovicoserrani-nautes!

**Comment by ludovicoserrani-nautes** [comment]
I made a branch (https://github.com/ludovicoserrani-nautes/mailing-esbuild-node/tree/mailing-0.7.2-next.1) with the upgraded package. 

To start the preview server I used the command `npx mailing@0.7.2-next.1`. 

`chokidar` seems to work, in fact the project recompiles when I save an edited file, but then I got a compilation error. 

The full log is:

```bash
mailing starting preview server
event - compiled client and server successfully in 641 ms (183 modules)
wait  - compiling...
event - compiled client and server successfully in 152 ms (183 modules)
mailing watching for changes to emails
mailing running preview at http://localhost:3883/
wait  - compiling / (client and server)...
event - compiled client and server successfully in 692 ms (267 modules)
mailing 200 / 947ms
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 365 ms (268 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling /api/previews...
wait  - compiling /previews/[previewClass]/[previewFunction] (client and server)...
event - compiled client and server successfully in 472 ms (310 modules)
event - compiled client and server successfully (321 modules)
mailing 200 /api/previews 1200ms
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
mailing 200 /previews/Welcome/toAmelita 1165ms
mailing 200 /previews/Welcome/toAmelita 1144ms
mailing 308 /api//previews/Welcome/toAmelita 2ms
wait  - compiling /api/previews/[moduleName]/[functionName]...
mailing 200 /icon-desktop.svg 38ms
mailing 200 /icon-mobile.svg 34ms
mailing 200 /icon-question.svg 37ms
mailing 200 /icon-send.svg 34ms
mailing 200 /icon-code.svg 50ms
event - compiled successfully in 204 ms (141 modules)
mailing 200 /api/previews/Welcome/toAmelita 307ms
mailing detected change on emails/Welcome.jsx, reloading
wait  - compiling...
error - ./src/emails/Welcome.jsx:14:0
Module not found: Can't resolve './components/BulletedList'
  12 |   MjmlSpacer,
  13 | } from "mjml-react";
> 14 | import BulletedList from "./components/BulletedList";
  15 | import ButtonPrimary from "./components/ButtonPrimary";
  16 | import {
  17 |   leadingTight,

Import trace for requested module:
./src/emails/previews/Welcome.jsx
./src/moduleManifest.ts
./src/util/moduleManifestUtil.ts
./src/pages/index.tsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling...
error - ./src/emails/Welcome.jsx:14:0
Module not found: Can't resolve './components/BulletedList'
  12 |   MjmlSpacer,
  13 | } from "mjml-react";
> 14 | import BulletedList from "./components/BulletedList";
  15 | import ButtonPrimary from "./components/ButtonPrimary";
  16 | import {
  17 |   leadingTight,

Import trace for requested module:
./src/emails/previews/Welcome.jsx
./src/moduleManifest.ts
./src/util/moduleManifestUtil.ts
./src/pages/index.tsx

https://nextjs.org/docs/messages/module-not-found
mailing 308 /api//previews/Welcome/toAmelita 2ms
mailing 200 /api/previews/Welcome/toAmelita 75ms
```

Don't know if this can be related to the original issue or it's something else.

**Comment by psugihara** [comment]
O no, thanks for testing, @ludovicoserrani-nautes I'll boot up an ubunutu vm today and try to repro.

**Comment by mrlubos** [comment]
@psugihara this is starting to look more like the issues I see in #129, so I'm exciting by this thing breaking 😀

**Comment by psugihara** [comment]
> I made a branch (https://github.com/ludovicoserrani-nautes/mailing-esbuild-node/tree/mailing-0.7.2-next.1)

confirmed this works fine on my macbook, grabbing an ubuntu vm now

**Comment by psugihara** [comment]
ok yep, seeing what you're seeing on my ubuntu vm. hmmmmm...

<img width="1420" alt="Screen Shot 2022-08-31 at 4 38 31 PM" src="https://user-images.githubusercontent.com/282016/187803328-48835049-69b8-44cf-84b2-e675f85faa67.png">

**Comment by psugihara** [comment]
Weird... the second time I booted mailing, I did not encounter this problem. I think there is potentially a race condition with copying files around here where we copy emails from userspace to `.mailing`. Will dig around more tomorrow.

**Comment by psugihara** [comment]
didn't mean to close but did merge some fixes in that made it work for me on ubuntu. In particular...
watch fix: #155
bundling fix: #154 


@ludovicoserrani-nautes can you let me know if this is fixed for you in the latest release 0.7.3?

Thanks!

**Comment by ludovicoserrani-nautes** [comment]
Yes, it works! Thank you for the support!

**Comment by psugihara** [comment]
hell yes. thanks for testing! 🤝
