### ISSUE TITLE
Error loading configPath in preview server

### ISSUE THREAD

**Issue by willviles** [sofn-xyz/mailing#181]
Since upgrading to `0.7.6`, I've noticed the `buildSendMail` function requires a `configPath` to be passed to it. 

However, despite passing the relative path to my `mailing.config.json` the preview server (including test sending) works fine, but logs an error whilst trying to read the config from within the Next.js pages folder: 

```bash
mailing error loading config at /my/path/to/monorepo/packages/email/.mailing/.next/server/pages/mailing.config.json
```

The error is logged in the command line, but not in the browser console.

**Comment by alexfarrill** [comment]
Thanks for reporting @willviles , we'll take a look

**Comment by psugihara** [comment]
We switched this to a debug message in the 0.7.7 release so you shouldn't see it anymore. We'll figure out a better scheme in the future if it becomes more important to match CLI anonymousIDs with sendMail usage.

Thanks again @willviles!
