### ISSUE TITLE
TypeError in Next.js app

### ISSUE THREAD

**Issue by dropocol** [sofn-xyz/mailing#182]
Hi, I am trying to install mailing as part of my Next.js application.

I ran the commands mentioned below.
1. npm install --save mailing mailing-core
2. npm install --save nodemailer

Now when I run npx mailing, I get the following error
TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.

I've tried setting up a fresh Next.js project and installed mailing but the result is same.

Any possible solution for this issue?

**Comment by dropocol** [comment]
Another thing I noticed is that it's happening due to multiple next.js installations.

I setup a project with mailing, mailing-core, react and react-dom and it worked. Then I added Next.js and it's showing the error I mentioned above.

**Comment by alexfarrill** [comment]
Thanks for reporting @dropocol .  I'm having trouble reproducing the error, but i'll keep trying.  Would it be possible for you to send us a sample repo that reproduces the error?  Also is it possible that you have any packages like nodemailer or next installed with your package manager globally? (`yarn global list` or `npm list -g`)  I could see that introducing a conflict. Thanks!

**Comment by psugihara** [comment]
We can now repro. Sorry about this.

Investigating...

**Comment by psugihara** [comment]
It appears to be a problem with running multiple versions of next (you can't!). We're moving next to a peer dependency and will ping this thread once we've released the fix.

**Comment by alexfarrill** [comment]
Hi @dropocol would you try version 0.7.7 and let us know if it fixes the problem?
Thanks!
Alex

**Comment by dropocol** [comment]
Hi @alexfarrill & @psugihara

I've tried the version 0.7.7 and I can confirm that it solved my issue. Thank you so much for taking care of it quickly.

**Comment by psugihara** [comment]
hell yeah, thx both
