### ISSUE TITLE
Option to minify HTML from export-previews

### ISSUE THREAD

**Issue by im-sticky** [sofn-xyz/mailing#189]
Currently it does not seem like there is any way to get the minified / collapsed whitespace version of the HTML files exported from `export-previews` command. Would it be possible to have the mjml compilation step of the build process minify the output by default, or have an optional argument for the command to minify the HTML?

**Comment by alexfarrill** [comment]
Thanks for the idea @im-sticky !  This was quick to implement and will be included in the next release (0.7.8).  If you have a moment to tell us a bit more about how you're using mailing, we'd love to hear more about it in this thread: https://github.com/sofn-xyz/mailing/discussions/121
