### ISSUE TITLE
mjml-react not maintained

### ISSUE THREAD

**Issue by seeARMS** [sofn-xyz/mailing#203]
FYI that as of 13 days ago, mjml-react is not maintained: https://github.com/wix-incubator/mjml-react

Not sure if there are supported alternatives that can be used?

**Comment by psugihara** [comment]
Quick update: I reached out to the maintainers to get more info about what's happening with mjml-react and figure out if it makes sense for us to maintain a fork.

**Comment by psugihara** [comment]
Good news, @faire is going to take over maintenance of mjml-react: https://github.com/wix-incubator/mjml-react/issues/92

I think this is a good outcome since they'll have more resources than our tiny bootstrapped team.

Going to close this now. Thanks for surfacing, @seeARMS!

**Comment by seeARMS** [comment]
Awesome!
