### ISSUE TITLE
default templates on demo.mailing.run have wrong background

### ISSUE THREAD

**Issue by alexfarrill** [sofn-xyz/mailing#216]
![IMG_F5E1AFA1B948-1](https://user-images.githubusercontent.com/24866/192053265-e02d7443-6ac6-430d-b129-b651999762d0.jpeg)

**Comment by psugihara** [comment]
hm, this is what I see:

<img width="450" alt="Screen Shot 2022-09-26 at 7 31 33 AM" src="https://user-images.githubusercontent.com/282016/192303383-89dc4c92-75e3-45e7-8aa7-bf7895e4eca6.png">
<img width="616" alt="Screen Shot 2022-09-26 at 7 31 39 AM" src="https://user-images.githubusercontent.com/282016/192303388-0b175461-6dfa-432b-b509-1b52c080bfa5.png">

are you on an android there?

**Comment by alexfarrill** [comment]
No, iPhone 13 Pro, iOS 15.3.1
Chrome and Safari both show the same thing

It's because of dark mode, light mode is working fine

**Comment by psugihara** [comment]
cannot repro on safari or chrome in iOS 15.6.1 or 16.0 😕
