### ISSUE TITLE
Safe delivery from development mode

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#245]
Usually in development mode we intercept emails and don't send them. Sometimes you do want to deliver from development mode for testing purposes (e.g. sending to Litmus or yourself for QA). Today you can get around that by passing the `forceDeliver` flag to `sendMail`, but that is pretty dangerous and not a very findable feature.

Let's ship 2 changes to mitigate this:

1. Change the name of `forceDeliver` to `dangerouslyForceDeliver` so that it is taken very seriously. I'd rather not pipe this type of delivery though the preview server because it is useful for testing what happens in prod.

2. [needs design] Add a button to the intercept screen (pictured) that allows you to actually deliver to recipients (or just a single email?). This should include a confirmation flow with the text **_"This email will be sent to 1,427 people. Are you sure you want to deliver?"_**. My hope is 99% of the deliver-from-dev use-cases will use this.

<img width="1395" alt="Screen Shot 2022-10-10 at 9 18 11 AM" src="https://user-images.githubusercontent.com/282016/194911110-ad72cb8d-9f73-41a4-9ba4-a443fcc0107d.png">

**Comment by monicakogler** [comment]
we can add a little notif to the intercept header, and for speed let's do HTML confirm dialog ⚡ 

<img width="1334" alt="Screen Shot 2022-10-11 at 7 52 35 PM" src="https://user-images.githubusercontent.com/609038/195238738-6602e70f-921b-4af3-a48d-b97e39e216cc.png">

https://www.figma.com/file/9SS4DwqxNZT0vnRalOKa8e/mailing?node-id=1757%3A7911

**Comment by psugihara** [comment]
released in 0.8.4 ✅
