### ISSUE TITLE
welcome email doesn't look so great in gmail

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#26]
not sure if webfonts are possible, but fallback should be a sans-serif font.

<img width="1208" alt="Screen Shot 2022-07-15 at 12 37 22 PM" src="https://user-images.githubusercontent.com/282016/179298869-0cbe8db2-c9b3-42bd-b036-1e918a625f9b.png">

**Comment by dextel2** [comment]
what was done to fix this ?

**Comment by psugihara** [comment]
It was a long time ago but likely a mix of specifying font fallbacks and mjml.
