### ISSUE TITLE
Errors running getting started guide

### ISSUE THREAD

**Issue by orenmizr** [sofn-xyz/mailing#301]
**Describe the bug**
setup the project. run. exception fired.

**To Reproduce**
npm init
npm install --save mailing mailing-core next
npm install --save react react-dom
npx mailing init

failed on win/ubuntu

**workaround**: installed next12 and react17 -> worked.

**Comment by psugihara** [comment]
Hey @orenmizr, sorry for the problems and thanks for creating an issue!

Our end-to-end CI tests are green on ubuntu with [next 13.0 and react 18.2.0](https://github.com/sofn-xyz/mailing/actions/runs/3363481051/jobs/5576685463) so perhaps we're missing something we should test for.

Are you running ubuntu locally or in CI? What version?

Does it also work with react18? We support 17 for compatibility but 18 has been pretty stable for some time. I would definitely believe that there are edge cases with next13 that we have not caught yet (but it's working well for us locally and in CI so far).

Unfortunately the windows issues are known (see #172) but I'm glad you found a workaround.

**Comment by alexfarrill** [comment]
Closing for now, but #172 is our ticket to support Windows.  Pull requests welcome!
