### ISSUE TITLE
mailing caught error Error: getaddrinfo ENOTFOUND smtp.example.com

### ISSUE THREAD

**Issue by crushingCodes** [sofn-xyz/mailing#316]
**Describe the bug**
Not able to get the test server to force send with the correct config settings, maybe im missing something. 
I tried changing /emails/index.ts transport, but still getting the following error.

```sh
mailing caught error Error: getaddrinfo ENOTFOUND smtp.example.com
```

even with /emails/index.ts config
```ts
const transport = nodemailer.createTransport({
  host: 'smtp.mailtrap.io',
  port: 2525,
  auth: {
    user: 'username',
    pass: 'password'
  }
});
```

**To Reproduce**

I must be missing a config step, but i updated the transport config in the /emails/index.ts, and when I run `npx mailing`, then send 

1. run npx mailing to init project inside nextjs app
2. change the config in emails/index.ts in transport ensuring host is different
3. restart mailing server
4. trigger send email within main nextjs app so it gets intercepted by mailing server
5. Click on 'Force send'
6. See error
```
mailing caught error Error: getaddrinfo ENOTFOUND smtp.example.com
```

**Expected behavior**
To send email to mailtrap

I was able to get it to send within the main nextjs app by doing  
dangerouslyForceDeliver: true 
inside sendMail

Any help would be appreciated

**Comment by psugihara** [comment]
Thanks for making an issue!

I was able to repro and I think I spotted the bug. Sorry about that.

Fixing shortly and will ping this thread upon release.

**Comment by SSardorf** [comment]
I'm having the same issue

**Comment by psugihara** [comment]
fixed in 0.8.15

thanks @SSardorf and @crushingCodes for finding this!

**Comment by crushingCodes** [comment]
@psugihara thanks for sorting it out so fast

**Comment by psugihara** [comment]
no problem, thx for reporting!

please lmk if you hit any other snags.
