### ISSUE TITLE
Email drawer takes up entire screen

### ISSUE THREAD

**Issue by JLHasson** [sofn-xyz/mailing#319]
**Describe the bug**
The email drawer on the left is taking up the entire screen, leading to desktop emails not displaying and the "send email" button being off screen:

![image](https://user-images.githubusercontent.com/2087380/200637780-4bac319c-d91c-4343-b638-1f34d576493e.png)

**To Reproduce**

1. yarn install
2. yarn mailing server build
3. yarn mailing server start
4. go to http://localhost:3000/previews

**Expected behavior**

**Screenshots**
Screenshot above

**Desktop (please complete the following information):**

- OS: macOS
- Browser Safari & Chrome
- Version Safari 15.6.1 & Chrome 107.0.5304.87 & Chrome 

**Smartphone (please complete the following information):**
N/A

**Additional context**
Happened on `mailing 0.8.14`, package.json:
```
{
  "name": "nextjs-tailwindcss-typescript-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "build:stg": "cp .env.staging .env.production && next build",
    "start:stg": "next start",
    "test": "jest --watch --runInBand",
    "test:ci": "jest --ci --runInBand"
  },
  "dependencies": {
    "@netlify/plugin-nextjs": "^4.9.1",
    "@types/react": "^18.0.18",
    "mailing": "^0.8.14",
    "mailing-core": "^0.8.14",
    "next": "^12.3.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@testing-library/dom": "^8.17.1",
    "@testing-library/react": "^13.3.0",
    "@types/node": "^16.10.1",
    "autoprefixer": "^10.3.6",
    "msw": "^0.46.1",
    "postcss": "^8.3.8",
    "postcss-import": "^14.0.2",
    "prettier": "2.7.1",
    "typescript": "^4.4.3",
    "whatwg-fetch": "^3.6.2"
  }
}
```

**Comment by psugihara** [comment]
Thanks for making this. Closing for now since you got unblocked with latest versions and we weren't able to repro. Please re-open if you still need help here though.
