### ISSUE TITLE
Can't resolve "emails"

### ISSUE THREAD

**Issue by tpmh31292** [sofn-xyz/mailing#330]
Hi, I add mailing to my current nextjs project and the `npx mailing` working and the preview server is up.

However, when I start my project and try to use `sendMail `from my nextjs API, I got an error `Module not found: Can't resolve 'emails'`

I have `import { sendMail } from 'emails'`

What do I need to do?

**Comment by psugihara** [comment]
Hey @tpmh31292, thanks for trying mailing.

I'm guessing that is not the correct path to your emails directory in the import statement. If you correct that path to point to the emails directory (where index exports sendMail), it should work.

Feel free to ping me on discord if you need more help https://discord.com/invite/fdSzmY46wY
