### ISSUE TITLE
TP + LS QA

### ISSUE THREAD

**Issue by monicakogler** [sofn-xyz/mailing#344]
# TP

possible to put padding on the head and subheads to constrain the width of the text on desktop? if not, maybe line break on desktop?

**survey, new match**

- [ ] desktop head px: 32px
- [x] OR desktop line break after gift/s

**upcoming**

- [x] desktop subhead px: 84px

**footer** 

- [x] mobile: line break after “Need help?”

# LS

**footer**

- [x] terms/privacy/contact should be fontweight: 500
- [x] can there be two spaces around the interpuncts? “  ·  “ not “ · “

**invoice**

- [x] headline 32px on mobile
- [x] can for the “Messages (7,300…)” – can this either not wrap or add a line break after messages on mobile? 

**newsletter**

- [x] can there be horizontal padding around the white cards on mobile?
- [x] the blue text in the “keyword” box is supposed to be a link. just wanna make sure link styles in paragraphs will work correctly, ideally across the emails? looks like it works in the review email

**review**

- [x] can the thumbs up/down buttons both be 50% width? currently thumbs down is a bit wider

**Comment by psugihara** [comment]
- [x] TP
- [ ] LS
