### ISSUE TITLE
/signup works but redirects to 404 on success

### ISSUE THREAD

**Issue by psugihara** [sofn-xyz/mailing#350]
<img width="1226" alt="Screenshot 2022-11-19 at 11 27 23 AM" src="https://user-images.githubusercontent.com/282016/202868139-4322affb-2726-4740-8895-abbe08d2dd5c.png">

**Comment by alexfarrill** [comment]
is this in cypress tests or when running dev?
I think /signup should 301 to /settings if you have created an account (instead of 404).  would that solve the problem?

**Comment by psugihara** [comment]
yeah I saw it in dev. Agree that behavior seems good.
