### ISSUE TITLE
Error after installing, removing tailwind dependency possible?

### ISSUE THREAD

**Issue by Jarrodsz** [sofn-xyz/mailing#419]
<img width="955" alt="Screenshot 2022-12-12 at 03 31 17" src="https://user-images.githubusercontent.com/90145421/206948378-58f33c7a-ada6-40f0-971a-48011ac30859.png">

Would it be possible to remove the Tailwind Dependency?
Im not using tailwind in my project.

**Comment by psugihara** [comment]
Hi @Jarrodsz,

We use tailwind to build the preview server UI. Did it not install when you installed `mailing`? Do you have a different problem with the dependency? 

If you don't want to bring it to production, you can install the `mailing` package as a dev dependency (recommended) and tailwind will only be included in development.

**Comment by psugihara** [comment]
> I do like the rails mailer preview a little better though no offense

haha none taken, ActionMailer is great. Though I'd personally hate returning to `.erb` files.

Closing for now, lmk if you need help getting set up.
