### ISSUE TITLE
Preview files with dashes `-` are not used

### ISSUE THREAD

**Issue by oliverzheng** [sofn-xyz/mailing#430]
**Describe the bug**
https://github.com/sofn-xyz/mailing/blob/56aba39c80b84e5707a35676272fc35f066bb1aa/packages/cli/src/commands/preview/server/setup.ts#L23 seems to filter out files that contain `-`. Is there a reason for this? Some of the code I'm using has conventions to have kebab-case.

**To Reproduce**

Have a file that is named `previews/test-file.tsx`. See that Mailing.run doesn't pick it up.

**Expected behavior**
Mailing.run picks up the file.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
All versions.

**Smartphone (please complete the following information):**
All versions.

**Additional context**

**Comment by alexfarrill** [comment]
Hey @oliverzheng thanks for reporting that.  That looks like a mistake to me, sorry about that.  I have a PR open for a patch and it should be available in 0.9.9.  Thanks for using Mailing!

**Comment by oliverzheng** [comment]
Thank you, @alexfarrill! Mailing's great as a drop-in email previewer!
