### ISSUE TITLE
Production builds still try to live reload

### ISSUE THREAD

**Issue by oliverzheng** [sofn-xyz/mailing#438]
**Describe the bug**
In the developer console, I can see socket.io network requests being sent for a production build. E.g. on https://book-book-mailing.vercel.app/

**To Reproduce**

1. Go to https://book-book-mailing.vercel.app/previews/Reservation/reservationWithError
2. Open dev console
3. See network requests for pulling.

Weirdly, only some of the demos on the Mailing website experience this.

**Expected behavior**
No live reload happens on production build.

**Screenshots**
<img width="332" alt="image" src="https://user-images.githubusercontent.com/26022/219172183-bb316020-93bd-4687-b24a-c019b0e59110.png">

**Desktop (please complete the following information):**

- OS: Mac OS X 13.1
- Browser: Chrome
- Version: 109.0.5414.119

**Additional context**

**Comment by psugihara** [comment]
Good catch. Let's remove that by checking if NODE_ENV === "production"

**Comment by marcincodes** [comment]
@psugihara This issue can be closed. Fix was merged here: https://github.com/sofn-xyz/mailing/pull/483
