### ISSUE TITLE
Telemetry opt-out doesn't work

### ISSUE THREAD

**Issue by KATT** [sofn-xyz/mailing#439]
**Describe the bug**

Every time I run `npx mailing`, it injects an `anonymousId` in the `mailing.config.json`

**To Reproduce**

1. Go to `mailing.config.json`
2. Remove `"anonymousId"`-line
3. Run `npx mailing`

**Expected behavior**

`mailing.config.json` shouldn't change

**Actual behavior**

It injects a tracking ID on the `mailing.config.json` on start

**Desktop (please complete the following information):**

- OS: macOS
- Version `0.9.10`

**Comment by alexfarrill** [comment]
If you set that to null instead of removing the line it should do the trick.

**Comment by alexfarrill** [comment]
@KATT please let us know if that resolves the issue for you.  I updated the docs, since they say to remove it which, you're right, doesnt work.  Thanks
