### ISSUE TITLE
Bug: Getting server error when starting the preview server

### ISSUE THREAD

**Issue by TAKANOME-DEV** [sofn-xyz/mailing#449]
**Describe the bug**

Each time I run `npx mailing`, I get the following error: `ENOENT: no such file or directory, open  glify-js/lib/utils.js`

Another weird thing and not sure if I should open another issue is that I'm not getting any emails in my [ethereal account](https://ethereal.email/) even though everything looks fine :thinking: 
**To Reproduce**
I have a PR [here](https://github.com/TAKANOME-DEV/vidly-client/pull/79)
1. Go to [my pr](https://github.com/TAKANOME-DEV/vidly-client/pull/79)
2. Clone it
3. Install the deps
4. Run `pnpm dev:preview`

**Expected behavior**
I was expecting to see my email templates and be able to tweak them as needed...
**Screenshots**
![Screenshot from 2023-02-25 21-21-22](https://user-images.githubusercontent.com/79809121/221381274-11b913b0-a11d-4b62-af37-7d1b79bc34d3.png)

- not getting email even though it looks like it works
```sh
mailing 💌 opening sendMail preview {
  subject: 'Your FilmFiesta login link',
  to: 'test@example.com',
  component: {
    '$$typeof': Symbol(react.element),
    type: [Function: LoginLink],
    key: null,
    ref: null,
    props: {
      url: 'http://localhost:3000/api/auth/callback/email?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fmovies&token=a899db3230ee4515b0d3f5cbc69b4effcfd88f25fe0941d5876f18ef1d8c0100&email=test%40example.com'
    },
    _owner: null,
    _store: {}
  },
  html: 'omitted'
}
```
**Desktop (please complete the following information):**

- OS: Ubuntu 22
- Browser Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by psugihara** [comment]
Hey thanks for trying mailing and filing an issue. Unfortunately I think this is a problem with pnpm that we haven't shipped a solution for yet. We don't yet support pnpm (but a PR here would be very welcome). Here's the relevant issue #381. I'm going to close this and add a link here to the comment.

The log with `mailing 💌 opening sendMail preview` is telling you that it's opening the preview locally in your browser.

**Comment by DavidTParks** [comment]
I'm actually getting this error after installing with npm. This branch has the repro: https://github.com/DavidTParks/pixelfy/tree/mailing-run-integration
