### ISSUE TITLE
Error sending

### ISSUE THREAD

**Issue by valentinsacco** [sofn-xyz/mailing#472]
Hi!!
It's my first time trying to send transactional emails.
I was trying to implement SSO auth system in my app but I'm getting some errors. When I start preview server, I get an error about not being able to find a module (that module is 'path')(second image). Also, when I try to login with SSO, mail is intercepted by mailing, if I want to send it via postmark, pressing 'force send' button, it throw me an error, it say that transport is not configured, but I already configured my transport using nodemailer with postmark. 

**Screenshots**
[code]
![image](https://github.com/sofn-xyz/mailing/assets/32754145/7acb8d72-e22f-4cdc-ba2e-e1a49385c509)
[terminal]
![image](https://github.com/sofn-xyz/mailing/assets/32754145/86ec1007-77f7-4efd-a55e-fe7f0fc4d17e)
[alert]
![image](https://github.com/sofn-xyz/mailing/assets/32754145/51acac33-fe41-48e0-bfe6-cd043f59fb0f)

From, To and Subject was hidden

- OS: Windows 10
- Browser Chrome

PD: Sorry, it´s my first time opening an issue and also my English is not good.

**Comment by alexfarrill** [comment]
Hi @valentinsacco , nice to meet you!  Unfortunately mailing does not currently support Windows.  We are compiling information about it [here](https://github.com/sofn-xyz/mailing/issues/172) and would love to review a pull request if you feel that's something you'd like to help out with.
