### ISSUE TITLE
Is there an issue with starting the service ?

### ISSUE THREAD

**Issue by alan-francis** [sofn-xyz/mailing#60]
Is there an issue with starting the service which I am experiencing right now.
![Screenshot 2022-07-28 101527](https://user-images.githubusercontent.com/39818587/181422746-c49dd21e-bd73-406b-95b9-01053d2b2b60.png)

Anything I am missing?

Thanks in advance

**Comment by psugihara** [comment]
Hm, those installation warnings should be OK but there should be more output after "Starting preview server". 

Is there something running on port 3883? I've seen it do that when I already have mailing running in a different terminal (I'd like to fix that with a more helpful message). 

What does your package.json look like?

**Comment by alan-francis** [comment]
Hi, please have a look at  the screenshot below. I am using Ubuntu 20.04.4 LTS in a WSL.

![Screenshot 2022-07-29 080921](https://user-images.githubusercontent.com/39818587/181671480-dbdfa490-3046-467b-82c0-4220125aed00.png)

Thanks

**Comment by psugihara** [comment]
Great info, @alan-francis.

To my eyes the deps look good, though I'd try adding `react` and `@types/react-dom`.

Either way, I'll attempt to repro this weekend and see what I can find out.

Apologies for the bugs, I really appreciate your help as we sand out the rough edges.

**Comment by psugihara** [comment]
Hey @alan-francis, sorry for the delay. This worked on my macbook (`react` was added and `mailing` updated to latest). I'll add `react` and `react-dom` to the install scripts in the README. I was figuring people would be using this in a context where they already had both installed, but cool to see other contexts.

<img width="567" alt="Screen Shot 2022-08-02 at 10 32 59 AM" src="https://user-images.githubusercontent.com/282016/182437890-4c3ed848-de54-4566-b604-460982d58b9a.png">

LMK if you're still having trouble with those deps and I'll try to get on ubuntu for more testing.

**Comment by psugihara** [comment]
Closing for now but lmk if you're still having issues!

**Comment by alan-francis** [comment]
Hi @psugihara , thank you for the reply. But I am still getting errors.
![Screenshot 2022-08-05 092423](https://user-images.githubusercontent.com/39818587/182998403-db448ab6-8961-4f7b-8737-0f79df412404.png)
 
Thanks in advance

**Comment by psugihara** [comment]
@alan-francis sorry about that. can you try updating `mailing` and `mailing-core` to latest? There was a bugged release that you might have gotten (my bad!).

For clarity, I made a little example app here: https://github.com/successor-software/mailing-standalone-app

We really appreciate you trying it out, sorry for bugs. Let me know if you hit anything else or have feature requests as you use it.

Also, after you get it up I'd love to learn about your stack and how you send email.

**Comment by alexfarrill** [comment]
@alan-francis going to close this one -- the project internals have changed quite a bit over the last month. but please re-open if you are still experiencing this issue
