### ISSUE TITLE
Immersion UI: dark mode

### ISSUE THREAD

**Issue by monicakogler** [sofn-xyz/mailing#82]
This can be a global switch, we only need a dark mode now.

I think it's mostly just changing backgrounds and font colors.

black #11111
white #E4EBFA

<img width="888" alt="Screen Shot 2022-08-25 at 4 28 56 PM" src="https://user-images.githubusercontent.com/282016/186786388-8ae44392-64af-40dc-aa70-45d8b626306c.png">

**Comment by psugihara** [comment]
edited and re-purposed to ship w the immersion UI
